### ISSUE TITLE
Controller not detected 

### ISSUE THREAD

**Issue by P1an3t** [xboxdrv/xboxdrv#106]
Contents of gdb-xboxdrv.txt:
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from xboxdrv...(no debugging symbols found)...done.
(gdb) handle SIG33 pass nostop nopront  [K  [K  [Kint
Signal        Stop      Print   Pass to program Description
SIG33         No        No      Yes             Real-time event 33
(gdb) set pagination 0
(gdb) run --detach-keren  [K  [Knel   [K-driver
Starting program: /usr/bin/xboxdrv --detach-kernel-driver
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
xboxdrv 0.8.5 - http://pingus.seul.org/~grumbel/xboxdrv/
Copyright © 2008-2011 Ingo Ruhnke <grumbel@gmx.de>
Licensed under GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it under certain
conditions; see the file COPYING for details.

Controller:        Microsoft Xbox 360 Controller
Vendor/Product:    045e:028e
USB Path:          001:006
Controller Type:   Xbox360
[New Thread 0x7ffff3e2d700 (LWP 25517)]
[Thread 0x7ffff3e2d700 (LWP 25517) exited]

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7206b79 in libusb_get_next_timeout () from
/lib/x86_64-linux-gnu/libusb-1.0.so.0
(gdb) backtrace fi  [Kull
#0  0x00007ffff7206b79 in libusb_get_next_timeout () from
/lib/x86_64-linux-gnu/libusb-1.0.so.0
No symbol table info available.
#1  0x00007ffff7206db4 in ?? () from /lib/x86_64-linux-gnu/libusb-1.0.so.0
No symbol table info available.
#2  0x00007ffff7206e67 in libusb_handle_events_timeout_completed ()
from /lib/x86_64-linux-gnu/libusb-1.0.so.0
No symbol table info available.
#3  0x00007ffff7206fcf in libusb_handle_events () from
/lib/x86_64-linux-gnu/libusb-1.0.so.0
No symbol table info available.
#4  0x0000555555603ecc in ?? ()
No symbol table info available.
#5  0x00005555556106a7 in ?? ()
No symbol table info available.
#6  0x000055555558f289 in ?? ()
No symbol table info available.
#7  0x0000555555574bfc in ?? ()
No symbol table info available.
#8  0x00005555555732cd in ?? ()
No symbol table info available.
#9  0x00005555555731d7 in main ()
No symbol table info available.
(gdb) info registers
rax            0x7ffff7414348   140737341637448
rbx            0x0      0
rcx            0x7ffff720dd10   140737339514128
rdx            0x7fffffffe010   140737488347152
rsi            0x7fffffffdfe0   140737488347104
rdi            0x0      0
rbp            0x7fffffffe010   0x7fffffffe010
rsp            0x7fffffffdfa0   0x7fffffffdfa0
r8             0x0      0
r9             0x555555906f20   93824996110112
r10            0x8      8
r11            0x246    582
r12            0x7fffffffdfe0   140737488347104
r13            0x7fffffffe010   140737488347152
r14            0x7fffffffe0d0   140737488347344
r15            0x7fffffffe0c0   140737488347328
rip            0x7ffff7206b79   0x7ffff7206b79 <libusb_get_next_timeout+25>
eflags         0x10246  [ PF ZF IF RF ]
cs             0x33     51
ss             0x2b     43
ds             0x0      0
es             0x0      0
fs             0x0      0
gs             0x0      0
(gdb) x/16i $pc
=> 0x7ffff7206b79 <libusb_get_next_timeout+25>: mov    0x200(%rbx),%eax
   0x7ffff7206b7f <libusb_get_next_timeout+31>: xor    %ebp,%ebp
   0x7ffff7206b81 <libusb_get_next_timeout+33>: test   %eax,%eax
   0x7ffff7206b83 <libusb_get_next_timeout+35>: js     0x7ffff7206b98
<libusb_get_next_timeout+56>
   0x7ffff7206b85 <libusb_get_next_timeout+37>: add    $0x18,%rsp
   0x7ffff7206b89 <libusb_get_next_timeout+41>: mov    %ebp,%eax
   0x7ffff7206b8b <libusb_get_next_timeout+43>: pop    %rbx
   0x7ffff7206b8c <libusb_get_next_timeout+44>: pop    %rbp
   0x7ffff7206b8d <libusb_get_next_timeout+45>: pop    %r12
   0x7ffff7206b8f <libusb_get_next_timeout+47>: pop    %r13
   0x7ffff7206b91 <libusb_get_next_timeout+49>: retq
   0x7ffff7206b92 <libusb_get_next_timeout+50>: nopw   0x0(%rax,%rax,1)
   0x7ffff7206b98 <libusb_get_next_timeout+56>: lea    0xd0(%rbx),%r13
   0x7ffff7206b9f <libusb_get_next_timeout+63>: mov    %r13,%rdi
   0x7ffff7206ba2 <libusb_get_next_timeout+66>: callq  0x7ffff7201a30
<pthread_mutex_lock@plt>
   0x7ffff7206ba7 <libusb_get_next_timeout+71>: mov    0xc8(%rbx),%rax
(gdb) thread appa\  [K  [Kly all backtrace

Thread 1 (Thread 0x7ffff7fd8840 (LWP 25513)):
#0  0x00007ffff7206b79 in libusb_get_next_timeout () from
/lib/x86_64-linux-gnu/libusb-1.0.so.0
#1  0x00007ffff7206db4 in ?? () from /lib/x86_64-linux-gnu/libusb-1.0.so.0
#2  0x00007ffff7206e67 in libusb_handle_events_timeout_completed ()
from /lib/x86_64-linux-gnu/libusb-1.0.so.0
#3  0x00007ffff7206fcf in libusb_handle_events () from
/lib/x86_64-linux-gnu/libusb-1.0.so.0
#4  0x0000555555603ecc in ?? ()
#5  0x00005555556106a7 in ?? ()
#6  0x000055555558f289 in ?? ()
#7  0x0000555555574bfc in ?? ()
#8  0x00005555555732cd in ?? ()
#9  0x00005555555731d7 in main ()
(gdb) quit
A debugging session is active.

        Inferior 1 [process 25513] will be killed.

Quit anyway? (y or n)

**Comment by Grumbel** [comment]
Segfault should be fixed in the latest version, if there are any other problems left, feel free to reopen this bug report.
