### ISSUE TITLE
Support of XboxOne Controllers in the future? 

### ISSUE THREAD

**Issue by ekianjo** [xboxdrv/xboxdrv#117]
Just wondering, would it be possible, and is it planned?

**Comment by Grumbel** [comment]
The Linux kernel since 3.17 should have XboxOne controller support. Adding support to xboxdrv isn't planed at the moment, but you can use `--evdev` option in the meantime if you need to remap stuff from the kernel driver.

**Comment by Grumbel** [comment]
It's now in bcb11ceceb4e635580c65d45b9392c78fd7397e1
