### ISSUE TITLE
Steam won't detect controller

### ISSUE THREAD

**Issue by P1an3t** [xboxdrv/xboxdrv#122]
I am using xboxdrv and a xbox controller and everything seems to be working. When I launch xboxdrv it says the controller is available as dev/input/js0 but steam can't see it. I have read other places that the ubuntu steam has an error with this but I have not seen any fixes. How can I tell steam my controller is available as dev/input/js0?
Thanks, P1an3t

**Comment by Grumbel** [comment]
You have to configure the controller in Steams Big Picture or use `xboxdrv --mimic-xpad`. Or alternatively just stick with the xpad driver, there is little benefit in xboxdrv when you are using Steam.
