### ISSUE TITLE
guid difference for daemon

### ISSUE THREAD

**Issue by ajw1980** [xboxdrv/xboxdrv#128]
This took a while to figure out, but it seems that when xboxdrv is in daemon mode the controllers get a different guid than non-daemon mode. This non-daemon mode guid seems better because it actually matches a known sdl guid so sdl programs know how to use it. This is possibly this problem from steam as well: https://github.com/ValveSoftware/steam-for-linux/issues/2890

I am using an xbox 360 wireless receiver. Here is non-daemon mode with sdl2-jstest reporting the information:

 /home/mythtv/xboxdrv/bin/xboxdrv --silent --dbus disabled --wid 0 --led 6 --deadzone 4000 --force-feedback --mimic-xpad-wireless --trigger-as-button --detach-kernel-driver
/home/mythtv/xboxdrv/bin/xboxdrv --silent --dbus disabled --wid 1 --led 7 --deadzone 4000 --force-feedback --mimic-xpad-wireless --trigger-as-button --detach-kernel-driver

Found 2 joystick(s)

Joystick Name:     'Xbox 360 Wireless Receiver'
Joystick GUID:     030000005e0400001907000000010000
Joystick Number:    0
Number of Axes:     4
Number of Buttons: 17
Number of Hats:     0
Number of Balls:    0
GameController:
  Name:    'X360 Wireless Controller'
  Mapping: '030000005e0400001907000000010000,X360 Wireless Controller,a:b0,b:b1,back:b6,dpdown:b14,dpleft:b11,dpright:b12,dpup:b13,guide:b8,leftshoulder:b4,leftstick:b9,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b10,righttrigger:a5,rightx:a3,righty:a4,start:b7,x:b2,y:b3,'

Joystick Name:     'Xbox 360 Wireless Receiver'
Joystick GUID:     030000005e0400001907000000010000
Joystick Number:    1
Number of Axes:     4
Number of Buttons: 17
Number of Hats:     0
Number of Balls:    0
GameController:
  Name:    'X360 Wireless Controller'
  Mapping: '030000005e0400001907000000010000,X360 Wireless Controller,a:b0,b:b1,back:b6,dpdown:b14,dpleft:b11,dpright:b12,dpup:b13,guide:b8,leftshoulder:b4,leftstick:b9,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b10,righttrigger:a5,rightx:a3,righty:a4,start:b7,x:b2,y:b3,'

And here is daemon mode:

/home/mythtv/xboxdrv/bin/xboxdrv --daemon --detach --silent --dbus disabled --wid 0 --led 6 --deadzone 4000 --force-feedback --mimic-xpad-wireless --trigger-as-button --detach-kernel-driver --next-controller --wid 1 --led 7 --deadzone 4000 --force-feedback --mimic-xpad-wireless --trigger-as-button --detach-kernel-driver

Found 2 joystick(s)

Joystick Name:     'Xbox 360 Wireless Receiver'
Joystick GUID:     0000000058626f782033363020576900
Joystick Number:    0
Number of Axes:     4
Number of Buttons: 17
Number of Hats:     0
Number of Balls:    0
GameController:
  not a gamepad

Joystick Name:     'Xbox 360 Wireless Receiver'
Joystick GUID:     0000000058626f782033363020576900
Joystick Number:    1
Number of Axes:     4
Number of Buttons: 17
Number of Hats:     0
Number of Balls:    0
GameController:
  not a gamepad

**Comment by Grumbel** [comment]
SDL2 calculates the GUID like this:

```
SDL_memset(guid->data, 0, sizeof(guid->data));

/* We only need 16 bits for each of these; space them out to fill 128. */
/* Byteswap so devices get same GUID on little/big endian platforms. */
*(guid16++) = SDL_SwapLE16(inpid.bustype);
*(guid16++) = 0;

if (inpid.vendor && inpid.product && inpid.version) {
    *(guid16++) = SDL_SwapLE16(inpid.vendor);
    *(guid16++) = 0;
    *(guid16++) = SDL_SwapLE16(inpid.product);
    *(guid16++) = 0;
    *(guid16++) = SDL_SwapLE16(inpid.version);
    *(guid16++) = 0;
} else {
    SDL_strlcpy((char*)guid16, namebuf, sizeof(guid->data) - 4);
}
```

So what is happening here is that vendor/product/version are zero and SDL2 in turn uses the name of the device to generate `0000000058626f782033363020576900` which translates to `Xbox 360 Wi`.

Now we need to find out why vendor/product/version aren't set in daemon mode.
