### ISSUE TITLE
Mad Catz Street Fight IV SE different usbid than on list

### ISSUE THREAD

**Issue by dvs666** [xboxdrv/xboxdrv#130]
I was hoping to get it added to the list for next update or if anyone can tell me how I can add it to xpad_device.cpp for retropie use? I've been stumped by this for a few days and I can't seem to figure out where its located or how to add it. Thanks

**Comment by Grumbel** [comment]
Type `lsusb`, find the line that is your controller and post the output here and I'll add it to the next release. You can also use the ids directly without modifying xpad_device via:

xboxdrv --device-by-id VENDOR:PRODUCT

**Comment by Grumbel** [comment]
It got added in 5759931d1d5a529871caced9ff36795a2c70442c
