### ISSUE TITLE
Force xboxdrv to /dev/input/js1

### ISSUE THREAD

**Issue by wonx** [xboxdrv/xboxdrv#134]
I ocassionally use a wired usb controller for a second player in my pc. However, my main controller is a ps3 gamepad that I use wirelessly via sixad. The problem is that when xboxdrv starts, it takes up the js0 device even if the usb gamepad is not plugged in, and forces my wireless controller to be js1. Therefore, I cannot use my wireless controller for single player games, because xboxdrv will always be always player1.

Is there any way to force xboxdrv to be js1, or just to assign a js device when the usb controller is plugged? 

The only workaround I've found so far, is manually starting xboxdrv via commandline once the main (wireless) controller has been paired. Which is really a pain..

**Comment by Grumbel** [comment]
xboxdrv has no control over /dev/input/jsX mapping. However you can change the device naming via udev rules and force it to js:

http://www.reactivated.net/writing_udev_rules.html

Also worth to mention: Only very few old games use /dev/input/jsX these days, almost everything uses /dev/input/eventX, so you might need to change that instead.
