### ISSUE TITLE
new release version / git tag

### ISSUE THREAD

**Issue by anthraxx** [xboxdrv/xboxdrv#135]
Hey,

Please consider adding a new release, the last git tag is from 2013 (0.8.5).
It would be awesome to get a new release now and also more frequent minor version releases in the future. This would ease the packaging for distributions and your software would not be shipped in a state it was over 2 years ago :smile: 

cheers

**Comment by Pinkbyte** [comment]
I second this request from behalf of both Gentoo users and developers

**Comment by ryanerato** [comment]
+1 as a Gentoo user

**Comment by anthraxx** [comment]
new version arrived :+1:
v0.8.6 3f7d21a2560da7376446713357d03903da7ddf9f
