### ISSUE TITLE
Elcom JC-U3613M support

### ISSUE THREAD

**Issue by flight16** [xboxdrv/xboxdrv#157]
I just got my [Elecom JC-U3613M XBox 360 gamepad clone](http://www2.elecom.co.jp/peripheral/gamepad/jc-u3613m/) working with xboxdrv.  Here is the info: 

> $ lsusb
> Bus 001 Device 005: ID 056e:2004 Elecom Co., Ltd
> 
> osmc@osmc:~$ sudo /usr/bin/xboxdrv --device-by-id 056e:2004 --type xbox360
> 
> xboxdrv 0.8.5 - http://pingus.seul.org/~grumbel/xboxdrv/ 
> ...
> Controller:        unknown
> Vendor/Product:    056e:2004
> USB Path:          001:005
> Controller Type:   Xbox360
> 
> Your Xbox/Xbox360 controller should now be available as:
>  /dev/input/js0
>  /dev/input/event3

Can this controller and ID be added to xboxdrv?

**Comment by flight16** [comment]
Thanks for such a quick addition.

I'm sorry, I had a typo in the company name.  It should be "Elecom", not "Elcom."

**Comment by Grumbel** [comment]
Fixed.
