### ISSUE TITLE
Controller undetected (Xbox One, Debian)

### ISSUE THREAD

**Issue by ghost** [xboxdrv/xboxdrv#250]
Hi, I'm having trouble detecting my Xbox One gamepad with xboxdrv.

Using simple scanning with `sudo xboxdrv` returns:
```
-- [ ERROR ] ------------------------------------------------------
No Xbox or Xbox360 controller found
```

The controller is detected by `lsusb` as:
```
Bus 002 Device 015: ID 0e6f:02a5 Logic3 
```
And trying to specifically connect to the device with `sudo xboxdrv --device-by-path 002:015 --type xbox` returns the following error:

```
xboxdrv 0.8.8 - http://pingus.seul.org/~grumbel/xboxdrv/ 
Copyright © 2008-2011 Ingo Ruhnke <grumbel@gmail.com> 
Licensed under GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html> 
This program comes with ABSOLUTELY NO WARRANTY. 
This is free software, and you are welcome to redistribute it under certain conditions; see the file COPYING for details. 

Controller:        unknown
Vendor/Product:    0e6f:02a5
USB Path:          002:015
Controller Type:   Xbox Classic

-- [ ERROR ] ------------------------------------------------------
USBController::usb_find_ep(): couldn't find matching endpoint
```

_System: Debian Stretch, Gnome 3.22, Linux image 4.9.0-6-amd64
Controller: [Xbox One usb controller](http://a.co/arPDEpD) by [PDP](http://pdp.com) (works fine on windows)
xboxdrv version: [0.8.8-1](https://packages.debian.org/stretch/xboxdrv) (installed via apt)_

**Comment by Vrakfall** [comment]
Looking at the source code, it doesn't seem to be supported right now. Same for the `0e6f:02a6` my girlfriend just bought (couldn't test it tho but I wanted to give the number to add support as well).
`0e6f:02a6` should be called, on the box, "Stealth series - Revenant blue".
I hope it's just a matter of adding their hardware code to the list.
