### ISSUE TITLE
Disconnected devices aren't unregistred - System crash

### ISSUE THREAD

**Issue by V10lator** [xboxdrv/xboxdrv#35]
Today I disconnected a gamepad, then reconnected it and this is what I got from xboxdrv (xboxdrv -D -s --force-feedback) :
```
[ERROR] USBController::on_read_data(): USB read failure: 32: LIBUSB_TRANSFER_NO_DEVICE
[ERROR] XboxdrvDaemon::launch_controller_thread(): no free controller slot found, controller will be ignored: 007:003 046d:c21f 'Logitech F710'
```
Futuremore, when I tried to kill xboxdrv (with ctrl + c) the whole system froze.

**Comment by lucquera** [comment]
@V10lator The led lights still doesn't work with xpad here (the only one problem!). The led is working fine for you?

**Comment by tvannahl** [comment]
I am using `Linux 4.1.6` and a wireless X360 Controller. If I use `xpad` the led is constantly blinking. I can understand why the daemon would not get fixed, but it would be great if only xboxdrv would crash or exit if the Controller is unplugged. After that it would be possible to start a xboxdrv.service via udev.

At the current state that udev rule needs a `kill -9` on unplug which of course is not a good behavior.

**Comment by SebDaMuffin** [comment]
I manually patched the latest stable version of xboxdrv with the fix that V10lator suggested and it's been working nicely for a few days. I don't know the implications of the patch but it didn't take long to modify. If there are no drawbacks then I'd love to see this implemented soon.

**Comment by ask-compu** [comment]
im having this issue in xboxdrv 0.8.5-1 on ubuntu 14.04

**Comment by Lucbug** [comment]
Still occuring xboxdrv 0.8.5 Ubuntu 16.04
