### ISSUE TITLE
Support for Rock Candy Wired 360 controller

### ISSUE THREAD

**Issue by SteveEdson** [xboxdrv/xboxdrv#49]
Hi, 

I would like to help get the Rock Candy controller working with xboxdrv. I ran `usb-devices` with the following output:

```
T:  Bus=01 Lev=02 Prnt=02 Port=01 Cnt=02 Dev#=  6 Spd=12  MxCh= 0
D:  Ver= 2.00 Cls=ff(vend.) Sub=ff Prot=ff MxPS= 8 #Cfgs=  1
P:  Vendor=0e6f ProdID=021f Rev=01.00
S:  Manufacturer=Performance Designed Products
S:  Product=Rock Candy Gamepad for Xbox 360
S:  SerialNumber=0001F2BD
C:  #Ifs= 4 Cfg#= 1 Atr=a0 MxPwr=500mA
I:  If#= 0 Alt= 0 #EPs= 2 Cls=ff(vend.) Sub=5d Prot=01 Driver=(none)
I:  If#= 1 Alt= 0 #EPs= 4 Cls=ff(vend.) Sub=5d Prot=03 Driver=(none)
I:  If#= 2 Alt= 0 #EPs= 1 Cls=ff(vend.) Sub=5d Prot=02 Driver=(none)
I:  If#= 3 Alt= 0 #EPs= 0 Cls=ff(vend.) Sub=fd Prot=13 Driver=(none)
```

If anyone could tell me how to proceed, that would be great.

Thanks.

**Comment by cnschulz** [comment]
Hey, 

I know this is super old but I am having this same issue... supposedly fixed?

Im running OSMC 2015.06.01 on a raspberry pi2. Here is the output of usb-devices:

T:  Bus=01 Lev=02 Prnt=02 Port=01 Cnt=02 Dev#=  6 Spd=12  MxCh= 0
D:  Ver= 2.00 Cls=ff(vend.) Sub=ff Prot=ff MxPS= 8 #Cfgs=  1
P:  Vendor=0e6f ProdID=021f Rev=01.00
S:  Manufacturer=Performance Designed Products
S:  Product=Rock Candy Gamepad for Xbox 360
S:  SerialNumber=00018DEE
C:  #Ifs= 4 Cfg#= 1 Atr=a0 MxPwr=500mA
I:  If#= 0 Alt= 0 #EPs= 2 Cls=ff(vend.) Sub=5d Prot=01 Driver=(none)
I:  If#= 1 Alt= 0 #EPs= 4 Cls=ff(vend.) Sub=5d Prot=03 Driver=(none)
I:  If#= 2 Alt= 0 #EPs= 1 Cls=ff(vend.) Sub=5d Prot=02 Driver=(none)
I:  If#= 3 Alt= 0 #EPs= 0 Cls=ff(vend.) Sub=fd Prot=13 Driver=(none)

xboxdrv simply reports that no controllers are present.

Any ideas?

**Comment by Grumbel** [comment]
Try the 0.8.7 release.
