### ISSUE TITLE
Cannot use two controllers

### ISSUE THREAD

**Issue by tlhiv** [xboxdrv/xboxdrv#53]
When executing `xboxdrv -w 0`, a single controller works.  However, when executing another session (namely, `xboxdrv -w 1`), xboxdrv immediately segfaults.  Here is the output from the `xboxdrv -w 1` via GDB:

gdb --args xboxdrv -w 1
...
(gdb) run
Starting program: /usr/bin/xboxdrv -w 1
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
xboxdrv 0.8.5 - http://pingus.seul.org/~grumbel/xboxdrv/ 
Copyright © 2008-2011 Ingo Ruhnke <grumbel@gmx.de> 
Licensed under GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html> 
This program comes with ABSOLUTELY NO WARRANTY. 
This is free software, and you are welcome to redistribute it under certain 
conditions; see the file COPYING for details. 

Controller:        Microsoft Xbox 360 Wireless Controller (PC)
Vendor/Product:    045e:0719
USB Path:          001:006
Wireless Port:     1
Controller Type:   Xbox360 (wireless)

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff720a5e7 in libusb_get_next_timeout ()
   from /usr/lib64/libusb-1.0.so.0

**Comment by Grumbel** [comment]
This might have been fixed with 8566800c0993b39e46d4982144a08c484e0f0ed9
