### ISSUE TITLE
Wamo Pro Controller Support

### ISSUE THREAD

**Issue by mpelos** [xboxdrv/xboxdrv#68]
Hi @Grumbel.

I bought an Wamo Pro Controller recently (see the image link below), and it's a copy from xbox 360 controller. However when I tried to use in Ubuntu with xpad kernel module the buttons mapping are all wrong. I tried different ways to configure the buttons mapping correctly but I couldn't do it right.

Then I find xboxdrv, but unfortunately, and obviously, there is no support for Wamo Pro. I was wondering, is it hard to add support for this controller? Can I do it? What files exactly I have to write?

Thank Very much

Wamo Pro: https://lh6.googleusercontent.com/-zFBCjSqQfFk/UgrVQG63_xI/AAAAAAAAGBY/iFyZTYuoUnE/s400/wamo-pro-bluetooth-controller-06.jpg

**Comment by Grumbel** [comment]
Bluetooth controller won't work directly with xboxdrv. They can however be indirectly used via --evdev option.
