### ISSUE TITLE
Misspellings -- stuitable to suitable

### ISSUE THREAD

**Issue by lasers** [xboxdrv/xboxdrv#98]
./doc/xboxdrv.xml:3260: \<title>"Error: No stuitable uinput device found"\</title>
./doc/xboxdrv.1:2284:.SS "\(dqERROR: NO STUITABLE UINPUT DEVICE FOUND\(dq"
./src/linux_uinput.cpp:77: out << "\nError: No stuitable uinput device found, tried:" << std::endl;

s/stuitable/suitable

**Comment by Grumbel** [comment]
Fixed in fe81a01
